-- 蔬菜 (1-30)
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (1, 'cucumber', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (2, 'tomato', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (3, 'onion', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (4, 'carrot', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (5, 'broccoli', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (6, 'spinach', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (7, 'potato', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (8, 'lettuce', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (9, 'cabbage', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (10, 'cauliflower', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (11, 'kale', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (12, 'celery', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (13, 'zucchini', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (14, 'eggplant', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (15, 'pumpkin', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (16, 'bell pepper', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (17, 'chili pepper', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (18, 'radish', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (19, 'beetroot', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (20, 'sweet potato', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (21, 'corn', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (22, 'asparagus', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (23, 'artichoke', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (24, 'brussels sprouts', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (25, 'peas', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (26, 'turnip', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (27, 'leek', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (28, 'garlic', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (29, 'ginger', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (30, 'mushroom', 'ingredient');

-- 肉類 (31-50)
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (31, 'chicken', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (32, 'beef', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (33, 'pork', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (34, 'lamb', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (35, 'turkey', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (36, 'duck', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (37, 'bacon', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (38, 'sausage', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (39, 'ham', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (40, 'veal', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (41, 'salmon', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (42, 'tuna', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (43, 'shrimp', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (44, 'crab', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (45, 'lobster', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (46, 'oyster', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (47, 'scallop', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (48, 'clam', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (49, 'mussels', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (50, 'octopus', 'ingredient');

-- 類型 (51-65)
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (51, 'japanese', 'type');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (52, 'italian', 'type');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (53, 'chinese', 'type');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (54, 'mexican', 'type');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (55, 'indian', 'type');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (56, 'french', 'type');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (57, 'thai', 'type');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (58, 'spanish', 'type');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (59, 'greek', 'type');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (60, 'korean', 'type');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (61, 'vietnamese', 'type');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (62, 'mediterranean', 'type');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (63, 'american', 'type');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (64, 'german', 'type');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (65, 'taiwanese', 'type');

-- 鍋具 (66-80)
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (66, 'frying pan', 'cooker');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (67, 'saucepan', 'cooker');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (68, 'stockpot', 'cooker');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (69, 'pressure cooker', 'cooker');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (70, 'slow cooker', 'cooker');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (71, 'rice cooker', 'cooker');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (72, 'steamer', 'cooker');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (73, 'wok', 'cooker');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (74, 'grill pan', 'cooker');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (75, 'roasting pan', 'cooker');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (76, 'baking dish', 'cooker');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (77, 'dutch oven', 'cooker');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (78, 'cast iron skillet', 'cooker');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (79, 'fondue pot', 'cooker');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (80, 'griddle', 'cooker');

-- 更多食材 (81-180)
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (81, 'basil', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (82, 'oregano', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (83, 'thyme', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (84, 'rosemary', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (85, 'parsley', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (86, 'cilantro', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (87, 'mint', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (88, 'dill', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (89, 'chives', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (90, 'sage', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (91, 'bay leaf', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (92, 'tarragon', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (93, 'lemongrass', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (94, 'marjoram', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (95, 'fennel', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (96, 'cumin', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (97, 'paprika', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (98, 'turmeric', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (99, 'saffron', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (100, 'cardamom', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (101, 'cinnamon', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (102, 'nutmeg', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (103, 'clove', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (104, 'allspice', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (105, 'black pepper', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (106, 'white pepper', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (107, 'mustard seed', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (108, 'caraway', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (109, 'coriander', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (110, 'anise', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (111, 'star anise', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (112, 'vanilla', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (113, 'chili powder', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (114, 'cayenne pepper', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (115, 'juniper berry', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (116, 'garlic powder', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (117, 'onion powder', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (118, 'ginger powder', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (119, 'chili flakes', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (120, 'celery seed', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (121, 'mace', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (122, 'dried thyme', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (123, 'dried oregano', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (124, 'dried basil', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (125, 'dried rosemary', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (126, 'dried dill', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (127, 'dried parsley', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (128, 'dried sage', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (129, 'dried mint', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (130, 'dried chives', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (131, 'dried tarragon', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (132, 'dried marjoram', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (133, 'dried fennel', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (134, 'dried bay leaf', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (135, 'lemon zest', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (136, 'lime zest', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (137, 'orange zest', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (138, 'grapefruit zest', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (139, 'tamarind', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (140, 'sumac', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (141, 'fenugreek', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (142, 'bayberry', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (143, 'black garlic', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (144, 'pink peppercorn', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (145, 'green peppercorn', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (146, 'orange peppercorn', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (147, 'smoked paprika', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (148, 'chipotle powder', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (149, 'ground mustard', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (150, 'garam masala', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (151, 'herbes de provence', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (152, 'italian seasoning', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (153, 'cajun seasoning', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (154, 'old bay seasoning', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (155, 'five-spice powder', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (156, 'curry powder', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (157, 'berbere', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (158, 'harissa', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (159, 'zaatar', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (160, 'baharat', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (161, 'advieh', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (162, 'fajita seasoning', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (163, 'taco seasoning', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (164, 'poultry seasoning', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (165, 'steak seasoning', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (166, 'fish seasoning', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (167, 'barbecue rub', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (168, 'brining mix', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (169, 'lemon pepper', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (170, 'garlic salt', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (171, 'onion salt', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (172, 'celery salt', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (173, 'sea salt', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (174, 'kosher salt', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (175, 'himalayan salt', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (176, 'flaked salt', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (177, 'smoked salt', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (178, 'iodized salt', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (179, 'pink salt', 'ingredient');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (180, 'truffle salt', 'ingredient');

-- 鍋具 (181-200)
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (181, 'air fryer', 'cooker');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (182, 'deep fryer', 'cooker');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (183, 'toaster oven', 'cooker');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (184, 'microwave oven', 'cooker');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (185, 'blender', 'cooker');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (186, 'food processor', 'cooker');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (187, 'stand mixer', 'cooker');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (188, 'hand mixer', 'cooker');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (189, 'immersion blender', 'cooker');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (190, 'electric grill', 'cooker');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (191, 'panini press', 'cooker');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (192, 'waffle maker', 'cooker');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (193, 'popcorn maker', 'cooker');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (194, 'yogurt maker', 'cooker');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (195, 'rice cooker', 'cooker');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (196, 'slow cooker', 'cooker');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (197, 'pressure cooker', 'cooker');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (198, 'coffee maker', 'cooker');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (199, 'electric kettle', 'cooker');
INSERT INTO tag (tag_id, tag_name, tag_type) VALUES (200, 'bread machine', 'cooker');
